version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --name sivasakthi --region ap-south-1

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $DOCKERHUB_USERNAME/brain-tasks-app:latest .
      - echo Pushing Docker image...
      - docker push $DOCKERHUB_USERNAME/brain-tasks-app:latest

  post_build:
    commands:
      - echo Deploying application to EKS...
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
      - kubectl rollout restart deployment/brain-task-deployment
      - echo Deployment completed successfully.
